### ISSUE TITLE
Benchmark ann against other existing frameworks

### ISSUE THREAD

**Issue by atmb4u** [makingthematrix/ann#2]
It would be interesting to see how this one compares with other popular neural network frameworks like `Tensorflow`, `Torch` etc.

**Comment by makingthematrix** [comment]
It's still a long way before I will be able to do that. At the very least I would need a working evolutionary engine to teach the network. And now I have a new job, other projects, I moved to a new place, etc. I plan to go back to this project, but I treat it more like a hobby research stuff than a real thing. So it's low on my priority list right now.
